# -*- coding: utf-8 -*-
"""Projet_IA_Besoin_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_WgRZ94rOcoGf7HrcEytx8HwrxlvC9ri
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("../../BIG_DATA/data/Patrimoine_Arbore_Nettoye.csv")

def preparation_donnees(df):
    # Variables clés : haut_tot et tronc_diam pour l'apprentissage, lat et long pour positionner les arbres sur les cartes
    colonnes_utiles = ['haut_tot', 'tronc_diam', 'lat', 'long']
    df_prepare = df[colonnes_utiles].copy().dropna()

    # La donnée est en cm dans le CSV, on passe en mètres pour la hauteur (plus parlant)
    # Le tronc_diam est en cm
    df_prepare['haut_tot'] = df_prepare['haut_tot'] / 100

    scaler = StandardScaler()
    features = ['haut_tot', 'tronc_diam']
    X_scaled = scaler.fit_transform(df_prepare[features])

    # print("Moyenne après scaling:", X_scaled.mean(axis=0)) # On attend une valeur très faible (=0)
    # print("Écart-type après scaling:", X_scaled.std(axis=0)) # On attend la valeur 1

    return df_prepare, X_scaled, scaler

df_prepare, X_scaled, scaler = preparation_donnees(df)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score

def analyse_comparative_dbscan_kmeans(X):
    results = []

    # K-MEANS
    k_range = range(2, 11)
    metrics_km = {
        "inertia": [],
        "silhouette": [],
        "calinski": [],
        "davies": []
    }

    for k in k_range:
        km = KMeans(n_clusters=k, random_state=1, n_init=10)
        labels = km.fit_predict(X)

        # Calcul des scores
        sil = silhouette_score(X, labels)
        cal = calinski_harabasz_score(X, labels)
        dav = davies_bouldin_score(X, labels)

        metrics_km["inertia"].append(km.inertia_)
        metrics_km["silhouette"].append(sil)
        metrics_km["calinski"].append(cal)
        metrics_km["davies"].append(dav)

        results.append({
            "Algo": "K-Means",
            "Paramètres": f"k={k}",
            "n_clusters": k,
            "Silhouette": sil,
            "Calinski-Harabasz": cal,
            "Davies-Bouldin": dav,
            "Bruit (outliers)": 0
        })

    # Visualisation K-MEANS
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    # Coude (Inertie)
    axes[0, 0].plot(k_range, metrics_km["inertia"], 'bo-')
    axes[0, 0].set_title('Méthode du Coude (Inertie)')
    axes[0, 0].set_ylabel('Inertie')

    # Silhouette
    axes[0, 1].plot(k_range, metrics_km["silhouette"], 'ro-')
    axes[0, 1].set_title('Score de Silhouette (Max est mieux)')
    axes[0, 1].set_ylabel('Silhouette')

    # Calinski-Harabasz
    axes[1, 0].plot(k_range, metrics_km["calinski"], 'go-')
    axes[1, 0].set_title('Indice Calinski-Harabasz (Max est mieux)')
    axes[1, 0].set_ylabel('Score CH')

    # Davies-Bouldin
    axes[1, 1].plot(k_range, metrics_km["davies"], 'yo-')
    axes[1, 1].set_title('Indice Davies-Bouldin (Min est mieux)')
    axes[1, 1].set_ylabel('Score DB')

    for ax in axes.flat:
        ax.set_xlabel('Nombre de clusters (k)')
        ax.grid(True)

    plt.tight_layout()
    plt.savefig("assets/metriques_evaluation_kmeans.png")
    plt.show()

    # DBSCAN
    eps_values = [0.3, 0.4, 0.5]
    min_samples_values = [5, 10]

    for eps in eps_values:
        for ms in min_samples_values:
            db = DBSCAN(eps=eps, min_samples=ms)
            labels = db.fit_predict(X)
            n_clusters = len(set(labels)) - (1 if -1 in labels else 0)

            # On ne calcule les scores que si au moins 2 clusters existent (hors bruit)
            if n_clusters > 1:
                results.append({
                    "Algo": "DBSCAN",
                    "Paramètres": f"eps={eps}, min={ms}",
                    "n_clusters": n_clusters,
                    "Silhouette": silhouette_score(X, labels),
                    "Calinski-Harabasz": calinski_harabasz_score(X, labels),
                    "Davies-Bouldin": davies_bouldin_score(X, labels),
                    "Bruit (outliers)": list(labels).count(-1)
                })

    df_res = pd.DataFrame(results)

    # Tri par Silhouette
    df_res = df_res.sort_values(by="Silhouette", ascending=False)

    print(df_res.to_string(index=False))

    return df_res

analyse_comparative_dbscan_kmeans(X_scaled)

import plotly.express as px

def generer_carte(k_choisi):
    kmeans = KMeans(n_clusters=k_choisi, random_state=1, n_init=10)
    clusters = kmeans.fit_predict(X_scaled)
    df_prepare['cluster_id'] = clusters

    # Tri logique : on force l'ID 0 à être le plus petit en hauteur moyenne
    ordre = df_prepare.groupby('cluster_id')['haut_tot'].mean().sort_values().index
    mapping_tri = {old: str(new) for new, old in enumerate(ordre)}
    df_prepare['Categorie_ID'] = df_prepare['cluster_id'].map(mapping_tri)

    # Libellés selon le choix utilisateur
    noms_dynamiques = {i: f"Groupe {i}" for i in range(k_choisi)}

    if k_choisi == 2:
        noms_dynamiques = {0: "Petit", 1: "Grand"}
    elif k_choisi == 3:
        noms_dynamiques = {0: "Petit", 1: "Moyen", 2: "Grand"}

    df_prepare['Nom_Categorie'] = df_prepare['Categorie_ID'].astype(int).map(noms_dynamiques)

    liste_ordonnee = [noms_dynamiques[i] for i in range(k_choisi)]

    fig = px.scatter_map(
        df_prepare,
        lat="lat", lon="long",
        color="Nom_Categorie",
        size="haut_tot",
        hover_data=['haut_tot', 'tronc_diam'],
        category_orders={"Nom_Categorie": liste_ordonnee},
        map_style="open-street-map",
        zoom=12, height=600
    )
    fig.show()

try:
    nb = int(input("Nombre de catégories pour la carte ? (2 et 3 auto-générés) : "))
    generer_carte(2)
    generer_carte(3)
except:
    print("Entrée invalide.")
    generer_carte(2)
    generer_carte(3)

import joblib
from sklearn.cluster import KMeans

try:
    K_FINAL = int(input("Entrez le nombre final de catégories pour l'export (recommandé : 2 ou 3) : "))
except ValueError:
    print("Entrée invalide, utilisation de la valeur par défaut : 2")
    K_FINAL = 2

model_final = KMeans(n_clusters=K_FINAL, random_state=1, n_init=10)
clusters = model_final.fit_predict(X_scaled)

# Calcul des moyennes pour le mapping
df_tri = pd.DataFrame({'cluster_id': clusters, 'hauteur_m': df_prepare['haut_tot']})
moyennes = df_tri.groupby('cluster_id')['hauteur_m'].mean().sort_values()

ordre_ids = moyennes.index

# Gestion dynamique des noms
if len(ordre_ids) == 3:
    noms_labels = ["Petit", "Moyen", "Grand"]
elif len(ordre_ids) == 2:
    noms_labels = ["Petit", "Grand"]
else:
    # Pour k > 3, on génère des étiquettes numériques ou textuelles automatiques
    noms_labels = [f"Taille {i}" for i in range(len(ordre_ids))]

# Création du mapping sécurisé
mapping_noms = {int(cluster_id): noms_labels[i] for i, cluster_id in enumerate(ordre_ids)}
print(moyennes)

# Sauvegarde
joblib.dump(model_final, 'models/modele_arbres.pkl')
joblib.dump(scaler, 'models/scaler_arbres.pkl')
joblib.dump(mapping_noms, 'models/mapping_noms.pkl')

import joblib
import pandas as pd

def diagnostic_arbre():
    model = joblib.load('models/modele_arbres.pkl')
    scaler = joblib.load('models/scaler_arbres.pkl')
    mapping = joblib.load('models/mapping_noms.pkl')

    print(f"Diagnostic : ({len(mapping)} catégories)")
    h = float(input("Hauteur souhaitée en MÈTRES (ex: 15) : "))
    d = float(input("Diamètre souhaité en CM (ex: 100) : "))

    entree = pd.DataFrame([[h, d]], columns=['haut_tot', 'tronc_diam'])
    scaled = scaler.transform(entree)

    res_id = int(model.predict(scaled)[0])
    nom_final = mapping.get(res_id, "Inconnu")

    print(f"\nCet arbre est classé : {nom_final}")

diagnostic_arbre()